service: bancoTalentos

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221


functions:
  cadastrarCandidato:
    handler: src/handlers.cadastrarCandidato
    events:
      - httpApi:
          path: /candidato
          method: post
  buscarCandidatos:
    handler: src/handlers.buscarCandidatos
    events:
      - httpApi:
          path: /buscar
          method: get
  mock:
    handler: src/handlers.mockDados
    events:
      - httpApi:
          path: /mock
          method: post


custom:
  dynamodb:
    stages:
      - dev
    start:
      migrate: true
  serverless-offline:
    resourceRoutes: true

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CandidatosTable
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: candidadoID
            AttributeType: S
        KeySchema:
          - AttributeName: candidadoID
            KeyType: HASH